[pytest]
minversion = 8.0
testpaths = app/tests
python_files = test_*.py
python_functions = test_*
pythonpath = .
addopts =
    -ra
    --strict-config
    --strict-markers
    --cov=app
    --cov-config=.coveragerc
    --cov-report=term-missing
    --cov-fail-under=85
